config/routes.rb
Cms::Application.routes.draw do
  devise_for :users
  resources :orders

  resources :buyers

  resources :sellers

  resources :addresses

  resources :zones

  resources :items

  root :to => "orders#index"

  

end

app/models/seller.rb
class Seller < ActiveRecord::Base
    belongs_to :address
    accepts_nested_attributes_for :address, :reject_if => :all_blank, :allow_destroy => true
    validates :name, presence: true
    validates_associated :address
    #validates_presence_of :address
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
    @address = Address.new
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
    @address = Address.new
  end

  # GET /sellers/1/edit
  def edit
    @seller.address.zip_code = @seller.address.zip_code.to_s.gsub(/^([\d]{5})([\d]{3})$/, '\1-\2')
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        @address = Address.new
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      zip_code = params[:seller][:address_attributes][:zip_code]
      params[:seller][:address_attributes][:zip_code] = zip_code.gsub(/\D/, "")
      params.require(:seller).permit( :name, :address_id, address_attributes: [ :id, :address, :number, :complement, :city, :zone_id, :zip_code])
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, t(:error)) %> <%= t :error_message %></h2>

      <ul>
      <% @seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :address, @address do |address| %>
    <div class="field">
      <%= address.label :address %><br>
      <%= address.text_field :address %>
    </div>
    <div class="field">
      <%= address.label :number %><br>
      <%= address.text_field :number %>
    </div>
    <div class="field">
      <%= address.label :complement %><br>
      <%= address.text_field :complement %>
    </div>
    <div class="field">
      <%= address.label :city %><br>
      <%= address.text_field :city %>
    </div>
    <div class="field">
      <%= address.label :zone_id %><br>
      <%= address.select(:zone_id, Zone.all.collect {|c| [c.name, c.id]}) %>
    </div>
    <div class="field">
      <%= address.label :zip_code %><br>
      <%= address.text_field :zip_code %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sellers/address_fields.erb
<div class="field">
  <%= f.label :address %><br>
  <%= f.text_field :address %>
</div>
<div class="field">
  <%= f.label :number %><br>
  <%= f.text_field :number %>
</div>
<div class="field">
  <%= f.label :complement %><br>
  <%= f.text_field :complement %>
</div>
<div class="field">
  <%= f.label :city %><br>
  <%= f.text_field :city %>
</div>
<div class="field">
  <%= f.label :zone_id %><br>
  <%= f.select(:zone_id, Zone.all.collect {|c| [c.name, c.id]}) %>
</div>
<div class="field">
  <%= f.label :zip_code %><br>
  <%= f.text_field :zip_code %>
</div>

app/views/sellers/edit.html.erb
<h1><%= t '.editing' %></h1>

<%= render 'form' %>

<%= link_to t(:show), @seller %> |
<%= link_to t(:back), sellers_path %>

app/views/sellers/index.html.erb
<h1><%= t '.listing' %></h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= t '.name' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.name %></td>
        <td><%= link_to t(:show), seller %></td>
        <td><%= link_to t(:edit), edit_seller_path(seller) %></td>
        <td><%= link_to t(:delete), seller, method: :delete, data: { confirm: t(:confirm) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_seller_path %>

app/views/sellers/new.html.erb
<h1><%= t '.new' %></h1>

<%= render 'form' %>

<%= link_to t(:back), sellers_path %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t '.name' %>:</strong>
  <%= @seller.name %>
</p>

<p>
  <strong><%= t '.address' %>:</strong>
  <%= @seller.address.address %>
</p>

<p>
  <strong><%= t '.number' %>:</strong>
  <%= @seller.address.number %>
</p>

<p>
  <strong><%= t '.complement' %>:</strong>
  <%= @seller.address.complement %>
</p>

<p>
  <strong><%= t '.city' %>:</strong>
  <%= @seller.address.city %>
</p>

<p>
  <strong><%= t '.zone' %>:</strong>
  <%= @seller.address.zone.name %>
</p>

<p>
  <strong><%= t '.zip_code' %>:</strong>
  <%= @seller.address.zip_code.to_s.gsub(/^([\d]{5})([\d]{3})$/, '\1-\2') %>
</p>

<%= link_to t(:edit), edit_seller_path(@seller) %> |
<%= link_to t(:back), sellers_path %>